app_clubs/urls.py
from django.urls import path
from . import views

app_name = "app_clubs"

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('create-club/', views.CreateClub.as_view(), name='create_club'),
    path('<slug:cat>/list-clubs/', views.ListClubs.as_view(), name='list_clubs'),

    path('profile-user/', views.ProfileUser.as_view(), name='profile_user'),
    path('<slug:club_slug>/profile-user/<int:pk>/', views.ProfileUserClub.as_view(), name='profile_user_club'),

    path('page-error/<slug:type_error>/', views.PageError.as_view(), name='page_error'),
    path('<slug:club_slug>/delete-post/<slug:post_slug>', views.DeletePost.as_view(), name='delete_post'),
    path('<slug:club_slug>/edit-post/<slug:post_slug>', views.UpdatePost.as_view(), name='edit_post'),
    path('<slug:club_slug>/edit-club/', views.UpdateClubProfile.as_view(), name='edit_club_profile'),
    path('<slug:club_slug>/join-club/', views.JoinClub.as_view(), name='join_club'),
    path('<slug:club_slug>/create-post/', views.CreatePost.as_view(), name='create_post'),
    path('<slug:club_slug>/create-event/', views.CreateEvent.as_view(), name='create_event'),
    path('<slug:club_slug>/approve-members/', views.ApproveMembers.as_view(), name='approve_members'),
    path('<slug:club_slug>/profile-club/', views.ProfileClub.as_view(), name='profile_club'),
    path('<slug:club_slug>/show-content/<slug:content>/', views.ShowContent.as_view(), name='show_content'),
    path('<slug:club_slug>/detail-post/<slug:post_slug>/', views.DetailPost.as_view(), name='detail_post'),
    path('<slug:club_slug>/send-msg/<int:pk>/', views.SendMsg.as_view(), name='send_msg'),
    path('my-notifs/', views.MyNotifs.as_view(), name='my_notifs'),
    path('<slug:club_slug>/delete-notifs/<int:pk>', views.DeleteNotifs.as_view(), name='delete_notifs'),

    path('<slug:club_slug>/detail-event/<int:pk>/', views.DetailEvent.as_view(), name='detail_event'),
]

project_clubs/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project_clubs import settings

urlpatterns = [
                  path('ckeditor5/', include('django_ckeditor_5.urls')),

                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls'), name='users'),
                  path('', include('app_clubs.urls')),
              ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("signup/", views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>/', views.UpdateProfile.as_view(), name='edit_profile'),
]

app_clubs/forms.py
from django.forms import ModelForm
from app_clubs.models import *
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget


class ClubForm(ModelForm):
    class Meta:
        model = Club
        fields = ('title', 'description', 'tg', 'cat', 'moderate', 'image')


class FormJoinClub(forms.Form):
    pass


class FormPost(ModelForm):
    class Meta:
        model = ModelPost
        fields = ['title', 'text', 'image', 'type_content']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            # 'text': forms.TextInput(attrs={'class': 'form-control', 'size': '40'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'type_content': forms.Select(attrs={'class': 'form-select form-select-lg mb-3'}),
            # "text": CKEditor5Widget(
            #     attrs={"class": "django_ckeditor_5"}
            # )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'class': 'form-control django_ckeditor_5'})


class FormEvent(ModelForm):
    class Meta:
        model = EventModel
        fields = ['title', 'description', 'format']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'format': forms.Select(attrs={'class': 'form-select form-select-lg mb-3'}),
        }


class FormNotifs(ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Notifs
        fields = ['text']

app_clubs/views.py
from django.shortcuts import render, redirect
from django.utils.text import slugify
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, TemplateView, FormView, DetailView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .utils import DataMixin, RequiredClubMember
from django.contrib.auth.mixins import LoginRequiredMixin
from pytils.translit import slugify
from django.contrib import messages


class ProfileUser(LoginRequiredMixin, DataMixin, TemplateView):
    template_name = 'app_clubs/profile_user.html'
    item_selected = 'profile_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_clubs'] = self.request.user.clubs.all()
        context['type_profile'] = 'my_page'

        return context


class ProfileUserClub(RequiredClubMember, TemplateView):
    template_name = 'app_clubs/profile_user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fio = get_user_model().objects.get(pk=self.kwargs['pk']).fio
        desc = get_user_model().objects.get(pk=self.kwargs['pk']).desc
        image = get_user_model().objects.get(pk=self.kwargs['pk']).image

        context['fio'] = fio
        context['desc'] = desc
        context['image'] = image
        context['club'] = self.request.current_club
        context['type_profile'] = 'foreign_profile'
        context['pk'] = self.kwargs['pk']

        return context


class SendMsg(RequiredClubMember, DataMixin, CreateView):
    template_name = 'app_clubs/send_msg.html'
    model = Notifs
    form_class = FormNotifs
    item_selected = 'my_msg'

    def get_success_url(self):
        messages.success(self.request, 'Сообщение отправлено')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.club = self.request.current_club
        receiver = get_user_model().objects.get(pk=self.kwargs['pk'])
        self.object = form.save()
        self.object.receiver.add(receiver)

        return super().form_valid(form)


class ProfileClub(RequiredClubMember, TemplateView):
    template_name = 'app_clubs/profile_club.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_club'] = self.request.current_club
        context['events'] = EventModel.objects.filter(club=self.request.current_club)
        context['posts'] = ModelPost.objects.filter(club=self.request.current_club)
        context['members'] = get_user_model().objects.filter(clubs=self.request.current_club)
        return context


class CreateClub(LoginRequiredMixin, DataMixin, CreateView):
    model = Club
    form_class = ClubForm
    template_name = 'app_clubs/create_club.html'
    item_selected = 'create_club'

    def get_success_url(self):
        messages.success(self.request, 'Клуб успешно создан')
        return reverse_lazy('app_clubs:list_clubs', kwargs={'cat': 'all'})

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        self.object = form.save()
        self.object.admins.add(self.request.user)
        self.request.user.clubs.add(self.object)
        return super().form_valid(form)


class ListClubs(LoginRequiredMixin, DataMixin, ListView):
    context_object_name = 'clubs'
    model = Club
    template_name = 'app_clubs/list_clubs.html'
    item_selected = 'list_clubs'

    def get_queryset(self):
        if self.kwargs['cat'] == 'all':
            return Club.objects.all()
        return Club.objects.filter(cat=self.kwargs['cat'])


class CreatePost(RequiredClubMember, DataMixin, CreateView):
    model = ModelPost
    form_class = FormPost
    template_name = 'app_clubs/create_post.html'
    for_admin = True
    item_selected = 'create_post'

    def get_success_url(self):
        messages.success(self.request, 'Пост создан')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title[:40] + f'{self.request.current_club}')
        form.instance.club = self.request.current_club
        form.instance.author = self.request.user

        return super().form_valid(form)


class JoinClub(LoginRequiredMixin, FormView):
    template_name = 'app_clubs/join_club.html'
    form_class = FormJoinClub

    def form_valid(self, form):
        current_user = self.request.user
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        self.request.current_club = current_club

        if not current_club.moderate:
            # Если не нужно модерировать
            current_user.clubs.add(current_club)
            return super().form_valid(form)
        else:
            # Если нужно модерировать
            # Просходит добавление пользователя в раздел not_approved
            current_club.not_approved.add(current_user)
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['club'] = Club.objects.get(slug=self.kwargs['club_slug'])

        return context

    def get_success_url(self):

        if self.request.current_club in self.request.user.clubs.all():
            return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

        messages.success(self.request, 'Вы были добавлены в клуб')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})


class ApproveMembers(RequiredClubMember, FormView, ListView):
    form_class = FormJoinClub
    template_name = 'app_clubs/not_approve_members.html'
    context_object_name = 'not_approved_members'
    for_admin = True

    def form_valid(self, form):
        user_id = self.request.POST['user_id']
        user_to_approve = get_user_model().objects.get(pk=user_id)

        current_club = self.request.current_club

        current_club.not_approved.remove(user_to_approve)
        user_to_approve.clubs.add(current_club)

        return super().form_valid(form)

    def get_queryset(self):
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        not_approved_members = current_club.not_approved.all()
        return not_approved_members

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        context['current_club'] = current_club.slug
        return context

    def get_success_url(self):
        messages.success(self.request, 'Вы добавили пользователя к клуб')
        return reverse_lazy('app_clubs:approve_members', kwargs={'club_slug': self.kwargs['club_slug']})


class CreateEvent(RequiredClubMember, DataMixin, CreateView):
    model = EventModel
    form_class = FormEvent
    template_name = 'app_clubs/create_event.html'
    for_admin = True

    def form_valid(self, form):
        # form.instance.slug = slugify(form.instance.title)
        current_club = self.request.current_club
        form.instance.club = current_club
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Событие создано')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})


class HomePage(TemplateView):
    template_name = 'app_clubs/index.html'
    extra_context = {'cats': cats}


class ShowContent(RequiredClubMember, ListView):
    extra_context = {'param': 'None'}
    template_name = 'app_clubs/show_content.html'

    def dispatch(self, request, *args, **kwargs):
        content_type = self.kwargs['content']
        if content_type not in ('events', 'posts', 'members'):
            return redirect(reverse_lazy('app_clubs:page_error', kwargs={'type_error': '404'}))

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        content_type = self.kwargs['content']
        self.extra_context['content_type'] = content_type
        self.extra_context['current_club'] = self.request.current_club
        self.context_object_name = content_type

        if content_type == 'events':
            self.model = EventModel
            return EventModel.objects.filter(club=self.request.current_club)

        if content_type == 'posts':
            self.model = ModelPost
            return ModelPost.objects.filter(club=self.request.current_club)

        if content_type == 'members':
            self.model = get_user_model()
            return get_user_model().objects.filter(clubs=self.request.current_club)


class DetailPost(RequiredClubMember, DetailView):
    model = ModelPost
    template_name = 'app_clubs/detail_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['club'] = self.request.current_club

        return context


class PageError(TemplateView):
    template_name = 'app_clubs/page_error.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        error = self.kwargs['type_error']
        if error == '404':
            context['text_error'] = 'Страница не найдена'
        if self.kwargs['type_error'] == '403':
            context['text_error'] = 'Доступ запрещен'

        return context


class DeletePost(RequiredClubMember, DeleteView):
    model = ModelPost
    template_name = 'app_clubs/delete_post.html'
    slug_url_kwarg = 'post_slug'
    for_admin = True

    def get_success_url(self):
        messages.success(self.request, 'Пост удален')

app_clubs/templates/app_clubs/create_club.html
{% extends 'app_clubs/base/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block content %}
    <br><br>
<div class="container">
    <h2>Создать клуб</h2><br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary">Сохранить</button>
    </form>

</div>
    <br><br><br>
{% endblock %}

app_clubs/templates/app_clubs/create_event.html
{% extends 'app_clubs/base/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block content %}
<form class="container" method="post">
    {% csrf_token %}
    {{ form.media }}

    {{ form.as_p }}


    <button type="submit" class="btn btn-secondary">Отправить</button>

</form>

{% endblock %}

app_clubs/templates/app_clubs/create_post.html
{% extends 'app_clubs/base/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <br><br>

    <form method="post" class="container" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Сохранить</button>
    </form>
    <br><br><br>
{% endblock %}

app_clubs/templates/app_clubs/delete_msg.html
{% extends 'app_clubs/base/base.html' %}

{% block content %}
<div class="container"><br>
    <form method="post">{% csrf_token %}
        <p style="font-size:30px">Вы действительно хотите удалить сообщение?</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

</div>

{% endblock %}

app_clubs/templates/app_clubs/delete_post.html
{% extends 'app_clubs/base/base.html' %}

{% block content %}
<div class="container"><br>
    <form method="post">{% csrf_token %}
        <p style="font-size:30px">Вы действительно хотите удалить пост?</p>
<!--        <input type="submit" value="Confirm">-->
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>

</div>

{% endblock %}

app_clubs/templates/app_clubs/detail_post.html
{% extends 'app_clubs/base/base.html' %}

{% block content %}

    <style>
        img {
            width: 100%;
            height: 100%;
        }
        p{
            font-size: 30px;
        }
    </style>
    <div class="container ck-content">

    <br>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|safe }}
    {% if request.user in club.admins.all %}
        <a href="{% url 'app_clubs:delete_post' post_slug=post.slug club_slug=post.club.slug %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'app_clubs:edit_post' post_slug=post.slug club_slug=post.club.slug %}" class="btn btn-secondary">Изменить</a>

    {% endif %}
    </div>

{% endblock %}

app_clubs/templates/app_clubs/index.html
{% extends 'app_clubs/base/base.html' %}
{% load static %}
{% load club_tags %}
{% block content %}

    {% show_main_img '596' %}
    <div class="container-fluid" style="border-bottom: 1px solid #101820">


        <div class="row block-lg">
            <div class="col-xs-12 col-lg-6" style="border-right: 1px solid #101820;">
                <br><br><br>
                <div class="ms-5">
                    <a href="{% url 'app_clubs:list_clubs' cat='all' %}" class="text-section-2">Хочу изучить <br>существующие
                        клубы</a>
                </div>
                <br>
                <br>
                <br>


            </div>
            <div class="col-xs-12 col-lg-6">
                <br><br><br>
                <div class="ms-5">
                    <a href="{% url 'app_clubs:create_club' %}" class="text-section-2">Хочу создать <br>свой клуб</a>
                </div>
            </div>
        </div>

        <div class="block-small">
            <br><br>
            <a href="{% url 'app_clubs:list_clubs' cat='all' %}" class="block-small-text">
                Хочу изучить существующие клубы</a><br><br>
            <hr>
            <hr>
            <br>
            <a href="{% url 'app_clubs:create_club' %}" class="block-small-text">Хочу создать свой клуб</a>
            <br><br>
        </div>
    </div>

    <br>
    <hr style="border-top:2px solid #101820">

    <br><br>

    <p class="ms-5 title-section block-lg">Направления:</p>
    <p class="text-center block-small-text-2 block-small">Направления:</p>

    <div class="container-fluid">
        <div class="row ms-4 me-4">
            <div class="col-lg-3">
                {% for cat in cats|slice:"0:3" %}
                    <div class="naprav-block">
                        <a href="{% url 'app_clubs:list_clubs' cat=cat.0 %}" class="">{{ cat.1 }}</a>
                    </div><br>
                {% endfor %}
            </div>
            <div class="col-lg-3">
                {% for cat in cats|slice:"3:6" %}
                    <div class="naprav-block">
                        <a style="color: black" href="{% url 'app_clubs:list_clubs' cat=cat.0 %}"
                           class="">{{ cat.1 }}</a>
                    </div><br>
                {% endfor %}
            </div>
            <div class="col-lg-3">
                {% for cat in cats|slice:"6:9" %}
                    <div class="naprav-block">
                        <a href="{% url 'app_clubs:list_clubs' cat=cat.0 %}" class="">{{ cat.1 }}</a>
                    </div><br>
                {% endfor %}
            </div>
            <div class="col-lg-3 block-lg">
                {% for cat in cats|slice:"9:" %}
                    <div class="naprav-block" style="height: 94%">
                        <a href="{% url 'app_clubs:list_clubs' cat=cats.9.0 %}"
                           class="flipped-text text-decoration-none">{{ cats.9.1 }}</a>
                    </div>
                    <br>
                {% endfor %}
                <br>
            </div>
            <div class="col-lg-3 block-small">
                {% for cat in cats|slice:"9:" %}
                    <div class="naprav-block">
                        <a href="{% url 'app_clubs:list_clubs' cat=cat.0 %}" class="">{{ cat.1 }}</a>
                    </div><br>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>


    <br><br><br>

{% endblock %}

app_clubs/templates/app_clubs/my_msg.html
{% extends 'app_clubs/base/base.html' %}


{% block content %}
    <br>
    <div class="container">
        <h1 class="title-weight-section">Мои сообщения</h1><br>

        <div class="list-group">
            {% for msg in notifs %}
                <div href="#" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <p class="mb-1">{{ msg.text }}</p>
                        <small class="text-body-secondary">{{ msg.timestamp }}</small>
                    </div>
                    {#                    <p class="mb-1">Some placeholder content in a paragraph.</p>#}
                    <small class="text-body-secondary">Отправитель: {{ msg.sender.fio }}</small><br>
                    <a href="{% url 'app_clubs:delete_notifs' club_slug=msg.club.slug pk=msg.pk %}" class="text-decoration-none"><small style="" class="text-body-secondary">Удалить</small></a>

                </div>


            {% endfor %}
        </div>
    </div>

{% endblock %}

app_clubs/templates/app_clubs/page_error.html
{% extends 'app_clubs/base/base.html' %}


{% block content %}
    <h1 class="container">{{ text_error }}</h1>
{% endblock %}

app_clubs/templates/app_clubs/profile_club.html
{% extends 'app_clubs/base/base.html' %}
{% load club_tags %}
{% load static %}
{% load club_filters %}
{% block content %}


<style>
        .img-post-list {
            height: 300px;
            background-size: cover;
            border: 1px solid white;
            border-radius: 4px;
        }

        .block-post-list {
            background-color: rgba(0, 0, 0, 0.32) !important;
            border: 1px solid white;
        }

        a{
            text-decoration:none;
        }




</style>

<div class="container"><br>
    <h1 class="" style="font-size: 54px; font-weight: bold">{{ current_club }}</h1>

    {% if current_club.short_desc %}
    <p style="font-size: 20px">{{ current_club.short_desc|safe }}</p>
    {% endif %}

{% if current_club.tg %}
    <h5><a href="{{ current_club.tg }}" style="color: black;" target="_blank">{{current_club.tg|tg_club }}</a></h5>
{% endif %}
</div>
<hr>
{% if request.user in current_club.admins.all %}
<br>

<div class="container">
{#    <a class="btn btn-outline-secondary" href="{% url 'app_clubs:create_post' club_slug=current_club.slug %}">Создать#}
{#        пост</a>#}
{#    <a class="btn btn-outline-secondary" href="{% url 'app_clubs:create_event' club_slug=current_club.slug %}">Создать#}
{#        событие</a>#}
{#    <a class="btn btn-outline-secondary"#}
{#       href="{% url 'app_clubs:approve_members' club_slug=current_club.slug %}">Подтвердить участников</a>#}
{#    <a class="btn btn-outline-secondary"#}
{#       href="{% url 'app_clubs:edit_club_profile' club_slug=current_club.slug %}">Редактировать профиль</a>#}

{#</nav>#}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page"
       href="{% url 'app_clubs:create_post' club_slug=current_club.slug %}">Создать пост</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page"
       href="{% url 'app_clubs:create_event' club_slug=current_club.slug %}">Создать событие</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page"
       href="{% url 'app_clubs:approve_members' club_slug=current_club.slug %}">Модерация</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page"
       href="{% url 'app_clubs:edit_club_profile' club_slug=current_club.slug %}">Редактировать профиль</a>
  </li>
</ul>

</div>


    <br>
{% endif %}
<div class="container">
{#    <a class="btn btn-outline-secondary" href="{% url 'app_clubs:my_notifs' club_slug=current_club.slug %}">Мои#}
{#        сообщения</a>#}
</div>
<br>

{#<div class="container-fluid">#}
{#    <div class="py-5" style="background-image: url({% static 'app_clubs/images/fon5.jpg' %});">#}
{#        <div class="container" data-cues="zoomIn" data-disabled="true">#}
{#            <div class="row bg-pattern bg-primary-gradient rounded-3 p-7 g-0" data-cue="zoomIn" data-show="true"#}
{#                 style="animation-name: zoomIn; animation-duration: 600ms; animation-timing-function: ease; animation-delay: 0ms; animation-direction: normal; animation-fill-mode: both;">#}
{#                <div class="col-xl-8 offset-xl-2 col-lg-10 offset-lg-1 col-md-12 col-12">#}
{#                    <div class="position-relative z-1 my-lg-5">#}
{#                        <div class="mb-5 text-center">#}
{#                            <h3 class="h2 text-white-stable mb-1">Хотите заказать товар?</h3>#}
{#                            <p class="mb-0 text-white-stable">Не уверены в своем выборе или нужна помощь в выборе товара? </p>#}
{#                        </div>#}
{#                        <form class="row g-2 needs-validation d-flex mx-lg-7" novalidate="">#}
{#                            <div class="col-md-7 col-xl-7 col-12">#}
{#                                <label for="notificationEmail" class="visually-hidden"></label>#}
{#                                <input type="email" id="notificationEmail" class="form-control"#}
{#                                       placeholder="ссылка на тг-аккаунт или email" aria-label="Enter your business email"#}
{#                                       required="">#}
{#                                <div class="invalid-feedback text-start">Please choose a email.</div>#}
{#                            </div>#}
{#                            <div class="col-md-5 col-xl-5 col-12">#}
{#                                <div class="d-grid">#}
{#                                    <button class="btn btn-dark" type="submit">Связаться со мной</button>#}
{#                                </div>#}
{#                            </div>#}
{#                        </form>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<br>
{% include 'app_clubs/base/base_show_events.html' with param='3:3' %}

<br>
{% include 'app_clubs/base/base_show_posts.html' with param='3:6' %}

<br><br><br>
{% include 'app_clubs/base/base_show_members.html' with param="4:4" %}

<br><br><br>

{% endblock %}

app_clubs/templates/app_clubs/profile_user.html
{% extends 'app_clubs/base/base.html' %}
{% load static %}
{% block content %}

    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">

                {% if request.user.image and type_profile == 'my_page' %}

                    <img src="{{ request.user.image.url }}" class="img-fluid rounded-start"
                         style="height: 300px; width: 100%; object-fit: cover">

                {% endif %}

                {% if type_profile == 'foreign_profile' and image %}
                    <img src="{{ image.url }}" class="img-fluid rounded-start"
                         style="height: 300px; width: 100%; object-fit: cover">

                {% endif %}


            </div>
            <div class="col-md-6">
                <div class="card-body">
                    {% if type_profile == 'foreign_profile' %}
                        <h2 class="card-title">{{ fio }}</h2><br>
                        <p class="card-text">{{ desc|truncatechars:400 }}</p>
                        <a href="{% url 'app_clubs:send_msg' club_slug=club.slug pk=pk %}"
                           class="btn btn-secondary btn-black-white">Отправить сообщение</a>
                    {% endif %}

                    {% if type_profile == 'my_page' %}
                        <h2 class="card-title">{{ request.user.fio }}</h2><br>
                        <p class="card-text">{{ request.user.desc|truncatechars:400 }}</p>
                        <a href="{% url 'users:edit_profile' pk=request.user.pk %}"
                           class="btn btn-secondary btn-black-white">Редактировать профиль</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>



    <br><br>

    <br><br>


    {% if not fio %}



        <div class="container">
            <h1 class="title-weight-section">Мои клубы</h1><br>
            <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for club in my_clubs %}

                    <div class="col">
                        <div class="card h-100">
                            {% if club.image %}
                                <div style="overflow: hidden; height: 200px;">
                                    <img style="object-fit: cover; height: 100%; width: 100%;"
                                         src="{{ club.image.url }}" class="card-img-top">

                                </div>

                            {% endif %}
                            <div class="card-body">
                                <p class="card-title" style="font-size: 30px; font-weight: 600">{{ club.title }}</p>
                                <a href="{% url 'app_clubs:profile_club' club.slug %}"
                                   class="btn join-btn">Перейти <i class="bi bi-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
    {% endif %}
    <br><br><br><br><br>
{% endblock %}