app_clubs/urls.py
from django.urls import path
from . import views

app_name = "app_clubs"

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('create-club/', views.CreateClub.as_view(), name='create_club'),
    path('<slug:cat>/list-clubs/', views.ListClubs.as_view(), name='list_clubs'),

    path('profile-user/', views.ProfileUser.as_view(), name='profile_user'),
    path('<slug:club_slug>/profile-user/<int:pk>/', views.ProfileUserClub.as_view(), name='profile_user_club'),

    path('page-error/<slug:type_error>/', views.PageError.as_view(), name='page_error'),
    path('<slug:club_slug>/delete-post/<slug:post_slug>', views.DeletePost.as_view(), name='delete_post'),
    path('<slug:club_slug>/edit-post/<slug:post_slug>', views.UpdatePost.as_view(), name='edit_post'),
    path('<slug:club_slug>/edit-club/', views.UpdateClubProfile.as_view(), name='edit_club_profile'),
    path('<slug:club_slug>/join-club/', views.JoinClub.as_view(), name='join_club'),
    path('<slug:club_slug>/create-post/', views.CreatePost.as_view(), name='create_post'),
    path('<slug:club_slug>/create-event/', views.CreateEvent.as_view(), name='create_event'),
    path('<slug:club_slug>/approve-members/', views.ApproveMembers.as_view(), name='approve_members'),
    path('<slug:club_slug>/profile-club/', views.ProfileClub.as_view(), name='profile_club'),
    path('<slug:club_slug>/show-content/<slug:content>/', views.ShowContent.as_view(), name='show_content'),
    path('<slug:club_slug>/detail-post/<slug:post_slug>/', views.DetailPost.as_view(), name='detail_post'),
    path('<slug:club_slug>/send-msg/<int:pk>/', views.SendMsg.as_view(), name='send_msg'),
    path('my-notifs/', views.MyNotifs.as_view(), name='my_notifs'),
    path('<slug:club_slug>/delete-notifs/<int:pk>', views.DeleteNotifs.as_view(), name='delete_notifs'),

    path('<slug:club_slug>/detail-event/<int:pk>/', views.DetailEvent.as_view(), name='detail_event'),
]

project_clubs/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project_clubs import settings

urlpatterns = [
                  path('ckeditor5/', include('django_ckeditor_5.urls')),

                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls'), name='users'),
                  path('', include('app_clubs.urls')),
              ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("signup/", views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>/', views.UpdateProfile.as_view(), name='edit_profile'),
]

app_clubs/models.py
import datetime as datetime
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field



cats = [
    ("sport", "СПОРТ"),
    ("it", "IT"),
    ("cybersport", "КИБЕРСПОРТ"),
    ("literature", "ЛИТЕРАТУРА"),
    ("culture", "КУЛЬТУРА"),
    ("chatting", "ОБЩЕНИЕ"),
    ("painting", "РИСОВАНИЕ"),
    ("music", "МУЗЫКА"),
    ("handwork", "РУКОДЕЛИЕ"),
    ("another", "ДРУГОЕ"),
]


class BaseModel(models.Model):
    format_choices = [
        ("Онлайн", "Онлайн"),
        ("Офлайн", "Офлайн"),
    ]

    title = models.CharField(max_length=128, verbose_name='Заголовок')
    slug = models.SlugField(max_length=128, db_index=True, null=False, blank=True, unique=True)
    club = models.ForeignKey("Club", on_delete=models.SET_NULL, null=True, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        abstract = True


class Club(BaseModel):
    ages_permis = (
        ('with_out', 'Без возрастных ограничений'),
        ('age1', '12+'),
        ('age2', '16+'),
        ('age3', '18+'),
    )
    club = None
    title = models.CharField(max_length=128, verbose_name='Название')
    admins = models.ManyToManyField(get_user_model(), related_name='clubsadmins')
    not_approved = models.ManyToManyField(get_user_model(), related_name='notapproved', null=True, blank=True)

    description = models.TextField(blank=True, null=True, verbose_name='Информация о клубе')
    # short_desc = models.TextField(blank=True, null=True, verbose_name='Доп.информация о клубе')
    short_desc = CKEditor5Field(blank=True, null=True, verbose_name="Доп.информация о клубе", config_name='extends')
    moderate = models.BooleanField(default=False, verbose_name='Модерировать')

    image = models.FileField(upload_to='uploads/%Y/%m/%d/', default=None, null=True, blank=True,
                             verbose_name='Изображение')
    tg = models.CharField(max_length=256, null=True, blank=True, verbose_name='Телеграм')
    cat = models.CharField(max_length=64, choices=cats, verbose_name='Направления', null=True)
    age = models.CharField(max_length=32, choices=ages_permis, verbose_name='Возрастные ограничения', null=True, blank=True, default='with_out')

    class Meta:
        verbose_name_plural = 'Клубы'


class ModelPost(BaseModel):
    type_content_choices = [
        ('news', 'Новости'),
        ('article', 'Статьи'),
    ]

    text = CKEditor5Field(blank=True, null=True, verbose_name="Текст", config_name='extends')
    image = models.FileField(upload_to='uploads/posts/', default=None, null=True, blank=True,
                             verbose_name='Изображение')
    datetime = models.DateField(blank=True, null=True, default=datetime.date.today)
    type_content = models.CharField(max_length=32, choices=type_content_choices, verbose_name='Тип поста', null=True, blank=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Посты'
        ordering = ['-datetime']


class EventModel(BaseModel):
    slug = None
    description = RichTextField(blank=True, null=True, verbose_name="Описание события")
    format = models.CharField(max_length=16, choices=BaseModel.format_choices, verbose_name="Формат проведения")


    class Meta:
        verbose_name_plural = 'События'


class Notifs(models.Model):
    club = models.ForeignKey("Club", on_delete=models.SET_NULL, null=True, blank=True)
    text = models.TextField(verbose_name='Текст', null=True)
    sender = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=False, verbose_name='Отправитель')
    receiver = models.ManyToManyField(get_user_model(), related_name='notifs_receiver', null=True, blank=False, verbose_name='Получатель')
    timestamp = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время')

    class Meta:
        verbose_name_plural = 'Сообщения'

app_clubs/views.py
from django.shortcuts import render, redirect
from django.utils.text import slugify
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, TemplateView, FormView, DetailView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .utils import DataMixin, RequiredClubMember
from django.contrib.auth.mixins import LoginRequiredMixin
from pytils.translit import slugify
from django.contrib import messages


class ProfileUser(LoginRequiredMixin, DataMixin, TemplateView):
    template_name = 'app_clubs/profile_user.html'
    item_selected = 'profile_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_clubs'] = self.request.user.clubs.all()
        context['type_profile'] = 'my_page'

        return context


class ProfileUserClub(RequiredClubMember, TemplateView):
    template_name = 'app_clubs/profile_user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fio = get_user_model().objects.get(pk=self.kwargs['pk']).fio
        desc = get_user_model().objects.get(pk=self.kwargs['pk']).desc
        image = get_user_model().objects.get(pk=self.kwargs['pk']).image

        context['fio'] = fio
        context['desc'] = desc
        context['image'] = image
        context['club'] = self.request.current_club
        context['type_profile'] = 'foreign_profile'
        context['pk'] = self.kwargs['pk']

        return context


class SendMsg(RequiredClubMember, DataMixin, CreateView):
    template_name = 'app_clubs/send_msg.html'
    model = Notifs
    form_class = FormNotifs
    item_selected = 'my_msg'

    def get_success_url(self):
        messages.success(self.request, 'Сообщение отправлено')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.club = self.request.current_club
        receiver = get_user_model().objects.get(pk=self.kwargs['pk'])
        self.object = form.save()
        self.object.receiver.add(receiver)

        return super().form_valid(form)


class ProfileClub(RequiredClubMember, TemplateView):
    template_name = 'app_clubs/profile_club.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_club'] = self.request.current_club
        context['events'] = EventModel.objects.filter(club=self.request.current_club)
        context['posts'] = ModelPost.objects.filter(club=self.request.current_club)
        context['members'] = get_user_model().objects.filter(clubs=self.request.current_club)
        return context


class CreateClub(LoginRequiredMixin, DataMixin, CreateView):
    model = Club
    form_class = ClubForm
    template_name = 'app_clubs/create_club.html'
    item_selected = 'create_club'

    def get_success_url(self):
        messages.success(self.request, 'Клуб успешно создан')
        return reverse_lazy('app_clubs:list_clubs', kwargs={'cat': 'all'})

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        self.object = form.save()
        self.object.admins.add(self.request.user)
        self.request.user.clubs.add(self.object)
        return super().form_valid(form)


class ListClubs(LoginRequiredMixin, DataMixin, ListView):
    context_object_name = 'clubs'
    model = Club
    template_name = 'app_clubs/list_clubs.html'
    item_selected = 'list_clubs'

    def get_queryset(self):
        if self.kwargs['cat'] == 'all':
            return Club.objects.all()
        return Club.objects.filter(cat=self.kwargs['cat'])


class CreatePost(RequiredClubMember, DataMixin, CreateView):
    model = ModelPost
    form_class = FormPost
    template_name = 'app_clubs/create_post.html'
    for_admin = True
    item_selected = 'create_post'

    def get_success_url(self):
        messages.success(self.request, 'Пост создан')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title[:40] + f'{self.request.current_club}')
        form.instance.club = self.request.current_club
        form.instance.author = self.request.user

        return super().form_valid(form)


class JoinClub(LoginRequiredMixin, FormView):
    template_name = 'app_clubs/join_club.html'
    form_class = FormJoinClub

    def form_valid(self, form):
        current_user = self.request.user
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        self.request.current_club = current_club

        if not current_club.moderate:
            # Если не нужно модерировать
            current_user.clubs.add(current_club)
            return super().form_valid(form)
        else:
            # Если нужно модерировать
            # Просходит добавление пользователя в раздел not_approved
            current_club.not_approved.add(current_user)
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['club'] = Club.objects.get(slug=self.kwargs['club_slug'])

        return context

    def get_success_url(self):

        if self.request.current_club in self.request.user.clubs.all():
            return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})

        messages.success(self.request, 'Вы были добавлены в клуб')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})


class ApproveMembers(RequiredClubMember, FormView, ListView):
    form_class = FormJoinClub
    template_name = 'app_clubs/not_approve_members.html'
    context_object_name = 'not_approved_members'
    for_admin = True

    def form_valid(self, form):
        user_id = self.request.POST['user_id']
        user_to_approve = get_user_model().objects.get(pk=user_id)

        current_club = self.request.current_club

        current_club.not_approved.remove(user_to_approve)
        user_to_approve.clubs.add(current_club)

        return super().form_valid(form)

    def get_queryset(self):
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        not_approved_members = current_club.not_approved.all()
        return not_approved_members

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_club = Club.objects.get(slug=self.kwargs['club_slug'])
        context['current_club'] = current_club.slug
        return context

    def get_success_url(self):
        messages.success(self.request, 'Вы добавили пользователя к клуб')
        return reverse_lazy('app_clubs:approve_members', kwargs={'club_slug': self.kwargs['club_slug']})


class CreateEvent(RequiredClubMember, DataMixin, CreateView):
    model = EventModel
    form_class = FormEvent
    template_name = 'app_clubs/create_event.html'
    for_admin = True

    def form_valid(self, form):
        # form.instance.slug = slugify(form.instance.title)
        current_club = self.request.current_club
        form.instance.club = current_club
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Событие создано')
        return reverse_lazy('app_clubs:profile_club', kwargs={'club_slug': self.kwargs['club_slug']})


class HomePage(TemplateView):
    template_name = 'app_clubs/index.html'
    extra_context = {'cats': cats}


class ShowContent(RequiredClubMember, ListView):
    extra_context = {'param': 'None'}
    template_name = 'app_clubs/show_content.html'

    def dispatch(self, request, *args, **kwargs):
        content_type = self.kwargs['content']
        if content_type not in ('events', 'posts', 'members'):
            return redirect(reverse_lazy('app_clubs:page_error', kwargs={'type_error': '404'}))

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        content_type = self.kwargs['content']
        self.extra_context['content_type'] = content_type
        self.extra_context['current_club'] = self.request.current_club
        self.context_object_name = content_type

        if content_type == 'events':
            self.model = EventModel
            return EventModel.objects.filter(club=self.request.current_club)

        if content_type == 'posts':
            self.model = ModelPost
            return ModelPost.objects.filter(club=self.request.current_club)

        if content_type == 'members':
            self.model = get_user_model()
            return get_user_model().objects.filter(clubs=self.request.current_club)


class DetailPost(RequiredClubMember, DetailView):
    model = ModelPost
    template_name = 'app_clubs/detail_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['club'] = self.request.current_club

        return context


class PageError(TemplateView):
    template_name = 'app_clubs/page_error.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        error = self.kwargs['type_error']
        if error == '404':
            context['text_error'] = 'Страница не найдена'
        if self.kwargs['type_error'] == '403':
            context['text_error'] = 'Доступ запрещен'

        return context


class DeletePost(RequiredClubMember, DeleteView):
    model = ModelPost
    template_name = 'app_clubs/delete_post.html'
    slug_url_kwarg = 'post_slug'
    for_admin = True

    def get_success_url(self):
        messages.success(self.request, 'Пост удален')

app_clubs/templates/app_clubs/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<body>
<head>

<!--    <link type="text/css" href="{% static 'app_clubs/styles/main.css' %}" rel="stylesheet"/>-->
    <link rel="stylesheet" href="{% static 'app_clubs/styles/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</head>
<style>
    .asteriskField {
        display: none;
    }

    @font-face {
        font-family: 'NT_Sakharov';
        src: url('{% static 'app_clubs/fonts/NT Sakharov Result-VF.ttf' %}') format('truetype');
    }

    body {
        font-family: 'NT_Sakharov', sans-serif;
    }
</style>
{% include 'app_clubs/base/navbar.html' %}
{% include 'app_clubs/base/flash_msg.html' %}

{% block content %}
{% endblock %}


{#{% include 'app_clubs/base/footer.html' %}#}
</body>
</html>

app_clubs/templates/app_clubs/base/base_show_events.html
{% load static %}
{% load club_filters %}

{% if events %}
<div class="container">
    <h2 class="title-weight-section">События</h2><br>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for part in events|list_content:param %}

                        <div class="col">
                            <div class="card h-100" style="background-color: rgba(232,232,232,0.46);">

                                <div class="card-body">
{#                                    <p>{{ current_club }}</p>#}
                                    <a href="{% url 'app_clubs:detail_event' club_slug=current_club.slug pk=part.pk %}" class="card-title text-decoration-none"
                                       style="color: black; font-weight: 700">
                                        {{ part.title }}</a><br><br>
                                    <a class="card-text text-decoration-none" href="{% url 'app_clubs:detail_event' club_slug=current_club.slug pk=part.pk %}"
                                       style="color: black; font-weight: 500">
                                        {{ part.description|truncatechars:150|safe }}</a>

                                </div>
                            </div>
                        </div>
{#            <div class="card border-dark mb-3" style="max-width: 18rem;">#}
{#                <div class="card-header bg-transparent">{{ part.title }}</div>#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">Dark card title</h5>#}
{#                    <p class="card-text">{{ part.description|truncatechars:200|safe }}</p>#}
{#                </div>#}
{#            </div>#}

        {% endfor %}

    </div>
    <br>
    <a href="{% url 'app_clubs:show_content' club_slug=current_club.slug content='events' %}"
       class="more">Еще...</a>

</div>
    <br><br>
{% endif %}

app_clubs/templates/app_clubs/base/base_show_members.html
{% load static %}
{% load club_filters %}

<div class="container">
    <h1 class="title-weight-section">Участники</h1><br>
    <div class="row gy-5">

        {% for member in members|list_content:param %}



            <div class="col-12 col-md-6 col-lg-3">

                {% if member.image %}

                    <div class="mb-4 img-post-list"
                         style="background-image: url({{ member.image.url }}); border-radius: 25px; height: 250px">


                {% else %}

                {% endif %}
                </div>
                <div class="mb-4">
                    <p class="mb-1"><a href="{% url 'app_clubs:profile_user_club' club_slug=current_club.slug pk=member.pk %}" class="text-decoration-none"
                                       style="color: black; font-weight: 500; font-size: 20px">{{ member.fio }}</a>
                    </p>
                    <p style="color: rgba(0,0,0,0.44); font-size: 15px">{{ member.tg }}</p>
                    {% if member in current_club.admins.all %}
                        <span class="fs-6">
                        <p style="color: rgba(0,0,0,0.44); font-size: 15px">Админ</p>
                    </span>
                    {% else %}
                        <span>
                        <p style="color: rgba(0,0,0,0.44); font-size: 15px">Участник</p>
                        </span>
                    {% endif %}

                </div>
            </div>

        {% endfor %}

    </div>

    <a href="{% url 'app_clubs:show_content' club_slug=current_club.slug content='members' %}" class="more">Еще...</a>
</div>

app_clubs/templates/app_clubs/base/base_show_posts.html
{% load static %}
{% load club_filters %}



<div class="container">
    <h2 class="title-weight-section">Статьи и новости</h2><br>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts|list_content:param %}

            <div class="col">
                <div class="card h-100" style="border: none">

                    {% if post.image %}
                        <div class="img-post-list"
                             style="background-image: url({{ post.image.url }});">
                        </div>
                    {% else %}
                        <div class="img-post-list"
                             style="background-image: url({% static 'users/images/back_page_login.png' %});">
                        </div>
                    {% endif %}

                    <div class="card-img-overlay block-post-list">
                        <div>
                            <p class="card-text" style="color:white">{{ post.get_type_content_display  }}<i class="bi bi-dot"></i><small>{{ post.datetime }}</small></p>
                            <a href="{% url 'app_clubs:detail_post' club_slug=current_club.slug post_slug=post.slug %}" class="text-decoration-none">
                                <h5 class="card-title" style="color: white; font-weight: 600">{{ post.title }}</h5>
                            </a>
                        </div>


                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
    <br>
    <a href="{% url 'app_clubs:show_content' club_slug=current_club.slug content='posts' %}" class="more">Еще...</a>
</div>

app_clubs/templates/app_clubs/base/flash_msg.html
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <br>
    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
</div>

app_clubs/templates/app_clubs/base/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Кнопочные решения</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
    </ul>
  </footer>
</div>

app_clubs/templates/app_clubs/base/header_links.html
{% load static %}


    <link type="text/css" href="{% static 'app_clubs/styles/main.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>

app_clubs/templates/app_clubs/base/main_img.html
{% load static %}
{#<div class="container-photo"#}
{#         style="background-image: url('{% static 'app_clubs/images/main_page.png' %}') !important;">#}
{#        <div style="" class="container-photo-text container">#}
{#            <p class="" style="height: {{ height_img }}px !important; font-weight: 400; line-height: 1;">Помогаем <br> организовывать <br> клубную<br>#}
{#                деятельность</p>#}
{#        </div>#}
{#</div>#}

<div class="container-photo"
     style="height:{{ height_img }}px; background-image: url('{% static src %}') !important; width: 100%; opacity: {{ opacity }}">
    <div style="" class="container-photo-text container">
        {% if title %}
            <p class="text-main-image-media" style="font-weight: 400; line-height: 1;">{{ title }}</p>
        {% else %}

            <p class="" style="font-weight: 400; line-height: 1;">Помогаем <br> организовывать <br> клубную<br>
                деятельность</p>
        {% endif %}
    </div>
</div>

app_clubs/templates/app_clubs/base/navbar.html
<nav class="navbar navbar-expand-md bg-light navbar-light sticky-top fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{ main_page_url }}">{{ logo }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% for item in menu_navbar %}
                    {% if item.selected == item_selected %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ item.url }}" style="color: #989898 !important;">{{ item.name }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ item.url }}">{{ item.name }}</a>
                        </li>
                    {% endif %}

                {% endfor %}

            </ul>
        </div>
    </div>
</nav>