app_clubs/urls.py
from django.urls import path
from . import views

app_name = "app_clubs"

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page'),
    path('create-club/', views.CreateClub.as_view(), name='create_club'),
    path('<slug:cat>/list-clubs/', views.ListClubs.as_view(), name='list_clubs'),

    path('profile-user/', views.ProfileUser.as_view(), name='profile_user'),
    path('<slug:club_slug>/profile-user/<int:pk>/', views.ProfileUserClub.as_view(), name='profile_user_club'),

    path('page-error/<slug:type_error>/', views.PageError.as_view(), name='page_error'),
    path('<slug:club_slug>/delete-post/<slug:post_slug>', views.DeletePost.as_view(), name='delete_post'),
    path('<slug:club_slug>/edit-post/<slug:post_slug>', views.UpdatePost.as_view(), name='edit_post'),
    path('<slug:club_slug>/edit-club/', views.UpdateClubProfile.as_view(), name='edit_club_profile'),
    path('<slug:club_slug>/join-club/', views.JoinClub.as_view(), name='join_club'),
    path('<slug:club_slug>/create-post/', views.CreatePost.as_view(), name='create_post'),
    path('<slug:club_slug>/create-event/', views.CreateEvent.as_view(), name='create_event'),
    path('<slug:club_slug>/approve-members/', views.ApproveMembers.as_view(), name='approve_members'),
    path('<slug:club_slug>/profile-club/', views.ProfileClub.as_view(), name='profile_club'),
    path('<slug:club_slug>/show-content/<slug:content>/', views.ShowContent.as_view(), name='show_content'),
    path('<slug:club_slug>/detail-post/<slug:post_slug>/', views.DetailPost.as_view(), name='detail_post'),
    path('<slug:club_slug>/send-msg/<int:pk>/', views.SendMsg.as_view(), name='send_msg'),
    path('my-notifs/', views.MyNotifs.as_view(), name='my_notifs'),
    path('<slug:club_slug>/delete-notifs/<int:pk>', views.DeleteNotifs.as_view(), name='delete_notifs'),

    path('<slug:club_slug>/detail-event/<int:pk>/', views.DetailEvent.as_view(), name='detail_event'),
]

project_clubs/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project_clubs import settings

urlpatterns = [
                  path('ckeditor5/', include('django_ckeditor_5.urls')),

                  path('admin/', admin.site.urls),
                  path('users/', include('users.urls'), name='users'),
                  path('', include('app_clubs.urls')),
              ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("signup/", views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit-profile/<int:pk>/', views.UpdateProfile.as_view(), name='edit_profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    fio = models.CharField(max_length=64, verbose_name='ФИО', null=True, blank=False)
    clubs = models.ManyToManyField("app_clubs.Club", related_name='members_clubs')
    image = models.FileField(upload_to='uploads/users/%Y/%m/%d/', default='uploads/users/user_no_photo.jpg', null=True, blank=True, verbose_name='Аватарка',)
    tg = models.CharField(max_length=128, verbose_name="Имя пользователя в телеграм", null=True, blank=True)
    desc = models.TextField(null=True, verbose_name='Описание о себе', blank=True)

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, UserChangeForm
from django.forms import ModelForm
from django import forms


class UserForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, 'class': 'form-control block-opacity input-height',
                                      'placeholder': 'Имя пользователя'}))
    fio = forms.CharField(label='ФИО',
                          widget=forms.TextInput(
                              attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'ФИО'}))
    tg = forms.CharField(required=False, label='Телеграм',
                         widget=forms.TextInput(
                             attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'Телеграм'}))
    desc = forms.CharField(required=False, label='Описание',
                           widget=forms.Textarea(
                               attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'Описание'}))

    # image = forms.FileField(label='Картинка',
    #                         widget=forms.FileInput(
    #                             attrs={'class': 'form-control input-file-opacity', 'placeholder': 'Картинка'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-control block-opacity input-height',
                                                                  'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-control block-opacity input-height',
                                                                  'placeholder': 'Повторите пароль'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'fio', 'tg', 'desc', 'password1', 'password2']


class CustomUserChangeForm(UserChangeForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, 'class': 'form-control block-opacity input-height',
                                      'placeholder': 'Имя пользователя'}))
    fio = forms.CharField(label='ФИО',
                          widget=forms.TextInput(
                              attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'ФИО'}))
    tg = forms.CharField(label='Телеграм',
                         widget=forms.TextInput(
                             attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'Телеграм'}))
    desc = forms.CharField(label='Описание',
                           widget=forms.Textarea(
                               attrs={'class': 'form-control block-opacity input-height', 'placeholder': 'Описание'}))
    image = forms.FileField(label='Картинка',
                            widget=forms.FileInput(
                                attrs={'class': 'form-control input-file-opacity', 'placeholder': 'Картинка'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'fio', 'tg', 'desc', 'image']


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, 'class': 'form-control block-opacity input-height',
                                      'placeholder': 'Имя пользователя'}))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", 'class': 'form-control block-opacity input-height',
                   'placeholder': 'Пароль'}
        ),
    )

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import *
from django.contrib import messages
from django.contrib.auth import login as auth_login


class LoginUser(LoginView):
    template_name = 'users/login.html'
    item_selected = 'login'
    form_class = LoginForm

    def get_success_url(self):
        return reverse_lazy('app_clubs:profile_user')


class SignUp(CreateView):
    # После авторизации перенапрявлять на страницу профиль пользователя для

    form_class = UserForm
    template_name = 'users/signup.html'
    item_selected = 'signup'

    extra_context = {'height': '100%'}

    def get_success_url(self):
        return reverse_lazy('users:login')

    def form_valid(self, form):
        auth_login(self.request, form.save())
        messages.success(self.request, 'Вы зарегистрировались')
        return HttpResponseRedirect(reverse_lazy('app_clubs:profile_user'))


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = CustomUserChangeForm
    template_name = 'users/signup.html'
    extra_context = {'type_btn': 'Сохранить', 'height': '600px'}

    def get_success_url(self):
        messages.success(self.request, 'Профиль изменен')
        return reverse_lazy('app_clubs:profile_user')

users/templates/users/login.html
{% extends 'users/base/base.html' %}
{% load static %}
{% block content %}
    <a href="{% url 'app_clubs:home_page' %}" style="color: #101820">
        <i class="bi bi-box-arrow-in-left" style="margin-left: 40px; font-size: 50px"></i>
    </a>
    <style>
        @media screen and (min-width: 768px) {
            html,
            body {
                height: 100%;
                background-size: cover;
                background-image: url({% static 'users/images/back_page_login.png' %});
            }

            .block-opacity {
                background-color: rgba(170, 161, 161, 0.74) !important;
                /*border: 1px solid */
            }
            .input-height {
                height: 40px;
                width: 450px;
            }
        }

        @media screen and (max-width: 767px) {
            html,
            body {
                height: 100%;
                background-size: cover;
                background-color: rgba(170, 161, 161, 1) !important;
            }

            .input-height {
                height: 40px;
                width: 330px;
            }

            .block-opacity {
                background-color: rgba(170, 161, 161, 1) !important;
            }
        }


        .form-signin {
            max-width: 530px;
            padding-top: 100px;
            padding-bottom: 100px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <main style=""
          class="main-block-login block-opacity form-signin w-100 m-auto d-flex justify-content-center position-absolute top-50 start-50 translate-middle">
        <div class="">
            <form method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal" style="color: #FFFFFF; font-weight: bold !important;">Давайте
                    начинать!</h1><br>
                {{ form.username }}<br>
                {{ form.password }}<br>
                <button class="btn btn-secondary w-100 py-2" type="submit">Войти</button>
                <br><br>
                <a class="btn btn-outline-secondary w-100 py-2" href="{% url 'users:signup' %}">Зарегистрироваться</a>
            </form>

        </div>
    </main>

    {#    <main style="" class="">#}
    {#        <div class="container">#}
    {#            <form method="post">#}
    {#                {% csrf_token %}#}
    {#                <h1 class="h3 mb-3 fw-normal" style="color: #FFFFFF; font-weight: bold !important;">Давайте#}
    {#                    начинать!</h1><br>#}
    {#                {{ form.username }}<br>#}
    {#                {{ form.password }}<br>#}
    {#                <button class="btn btn-secondary w-100 py-2" type="submit">Войти</button>#}
    {#                <br><br>#}
    {#                <a class="btn btn-outline-secondary w-100 py-2" href="{% url 'users:signup' %}">Зарегистрироваться</a>#}
    {#            </form>#}
    {##}
    {#        </div>#}
    {#    </main>#}


{% endblock %}

users/templates/users/signup.html
{#{% extends 'users/base/base.html' %}#}
{#{% load crispy_forms_filters %}#}
{#{% load crispy_forms_tags %}#}
{##}
{#{% block content %}#}
{##}
{#    <div class="container">#}
{#        <form method="post" enctype="multipart/form-data">{% csrf_token %}#}
{#            {{ form|crispy }}#}
{#            <button type="submit" class="btn btn-primary">Сохранить</button>#}
{#        </form>#}
{#    </div>#}
{##}
{#{% endblock %}#}
{% extends 'users/base/base.html' %}
{% load static %}

{% block content %}
    <style>
        @media screen and (min-width: 768px) {
            html,
            body {
                height: 100%;
                background-size: cover;
                background-image: url({% static 'users/images/back_page_login.png' %});
            }

            .block-opacity {
                background-color: rgba(170, 161, 161, 0.74) !important;
                /*border: 1px solid */
            }
            .input-height {
                height: 40px;
                width: 450px;
            }
        }

        @media screen and (max-width: 767px) {
            html,
            body {
                height: 100%;
                background-size: cover;
                background-color: rgba(170, 161, 161, 1) !important;
            }

            .input-height {
                height: 40px;
                width: 330px;
            }

            .block-opacity {
                background-color: rgba(170, 161, 161, 1) !important;
            }
        }

        .form-signin {
            max-width: 530px;
            padding-top: 50px;
            padding-bottom: 50px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <a href="{% url 'app_clubs:home_page' %}" style="color: #101820" class="arrow-lg">
        <i class="arrow-lg bi bi-box-arrow-in-left" style="margin-left: 40px; font-size: 50px"></i>
    </a>

    <main style=""
          class="block-opacity form-signin w-100 m-auto d-flex justify-content-center position-absolute top-50 start-50 translate-middle">
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="h3 mb-1 fw-normal" style="color: #FFFFFF; font-weight: bold !important;">Давайте
                    начинать!</h1><br>
                {{ form.username }}<br>
                {{ form.fio }}<br>
                {{ form.tg }}<br>
                {{ form.desc }}<br>

                {% if form.image %}
                    {#                <p>Выбрать аватарку</p>#}
                    {{ form.image }} <br>
                {% endif %}

                {{ form.password1 }}<br>
                {{ form.password2 }} <br>

                {{ form.errors }}
                {% if type_btn %}

                    <button class="btn btn-secondary w-100 py-2" type="submit">{{ type_btn }}</button>
                {% else %}
                    <button class="btn btn-secondary w-100 py-2" type="submit">Зарегистрироваться</button>

                {% endif %}


                <br><br>
                <a class="btn btn-outline-secondary w-100 py-2" href="{% url 'users:login' %}">Войти</a><br><br>
                <a href="{% url 'app_clubs:home_page' %}" style="color: #101820" class="arrow-small">
                    <i class="bi bi-box-arrow-in-left" style="font-size: 50px"></i>
                </a>
            </form>

        </div>

    </main>



{% endblock %}